export type Patient = {
    firstname: string; // crm types
    lastname: string; // crm types
    birthdate: string | null; // exist as string
    date: {
        d: string;
        m: string;
        y: string;
    };
    accountName: string;
    addressStreet1: string;
    addressStreet2: string;
    addressStreet3: string;
    address1_fax?: string;
    preferredcontactmethodcode?: string;
    address1_city?: string | null;
    address1_stateorprovince?: string | null;
    address1_postalcode?: string | null;
    address1_country?: string;
    emailaddress1?: string;
    mobilephone?: string;
    relationshipType: string;
    new_npi?: string;
    ta_emrid?: string | null;
    ta_primaryinsurance?: any | null;
    'ta_primaryinsurance@odata.bind'?: string | null;
    ta_PrimaryInsurance?: any | null;
    'ta_PrimaryInsurance@odata.bind'?: string | null;
    ta_primarymemberid?: string;
    ta_secondaryinsurance?: any | null;
    'ta_secondaryinsurance@odata.bind'?: string | null;
    ta_SecondaryInsurance?: any | null;
    'ta_SecondaryInsurance@odata.bind'?: string | null;
    ta_secondarymemberid?: string;
    ta_originationsource?: string;
    parentcustomerid?: string;
    parentcustomerid_account?: any | null;
    'parentcustomerid_account@odata.bind'?: string | null;
    // crm types
    new_clinicnpi?: string | null;
    stageid?: string;
    traversedpath?: string;
    adx_identity_accessfailedcount?: string;
    address1_composite?: string;
    address1_addresstypecode?: string;
    address1_county?: string;
    address1_freighttermscode?: string;
    address1_latitude?: string;
    address1_longitude?: string;
    address1_name?: string;
    address1_telephone1?: string;
    address1_postofficebox?: string;
    address1_primarycontactname?: string;
    address1_line2?: string;
    address1_line3?: string;
    address1_telephone2?: string;
    address1_telephone3?: string;
    address1_line1?: string;
    address2_composite?: string;
    address2_addresstypecode?: string;
    address2_city?: string;
    address2_country?: string;
    address2_county?: string;
    address2_fax?: string;
    address2_latitude?: string;
    address2_longitude?: string;
    address2_name?: string;
    address2_postofficebox?: string;
    address2_primarycontactname?: string;
    address2_stateorprovince?: string;
    address2_line1?: string;
    address2_line2?: string;
    address2_line3?: string;
    address2_telephone1?: string;
    address2_telephone2?: string;
    address2_telephone3?: string;
    address2_postalcode?: string;
    address3_composite?: string;
    address3_addresstypecode?: string;
    address3_city?: string;
    address3_county?: string;
    address3_fax?: string;
    address3_latitude?: string;
    address3_longitude?: string;
    address3_name?: string;
    address3_postofficebox?: string;
    address3_primarycontactname?: string;
    address3_telephone1?: string;
    address3_telephone2?: string;
    address3_telephone3?: string;
    address3_country?: string;
    address3_stateorprovince?: string;
    address3_line1?: string;
    address3_line2?: string;
    address3_line3?: string;
    address3_postalcode?: string;
    ta_admin?: string;
    aging30?: string;
    aging30_base?: string;
    aging60?: string;
    aging60_base?: string;
    aging90?: string;
    aging90_base?: string;
    anniversary?: string;
    annualincome?: string;
    annualincome_base?: string;
    assistantname?: string;
    assistantphone?: string;
    isbackofficecustomer?: string;
    businesscard?: string;
    telephone1?: string;
    business2?: string;
    businesscardattributes?: string;
    callback?: string;
    childrensnames?: string;
    company?: string;
    adx_confirmremovepassword?: string;
    contactid: string;
    ta_contactrowid?: string;
    new_contacttype?: string;
    adx_createdbyipaddress?: string;
    adx_createdbyusername?: string;
    creditonhold?: string;
    creditlimit?: string;
    creditlimit_base?: string;
    customersizecode?: string;
    new_customertypes?: string;
    department?: string;
    description?: string;
    msdyn_disablewebtracking?: string;
    donotbulkemail?: string;
    donotbulkpostalmail?: string;
    donotemail?: string;
    donotfax?: string;
    donotpostalmail?: string;
    donotphone?: string;
    educationcode?: string;
    emailaddress2?: string;
    emailaddress3?: string;
    adx_identity_emailaddress1confirmed?: string;
    employeeid?: string;

    entityimage?: string;
    entityimageid?: string;
    exchangerate?: string;
    externaluseridentifier?: string;
    followemail?: string;
    ftpsiteurl?: string;
    fullname?: string;
    msdyn_gdproptout?: string;
    gendercode?: string | null;
    ikl_geocoderecord?: string;
    governmentid?: string;
    haschildrencode?: string;
    telephone2?: string;
    home2?: string;
    importsequencenumber?: string;
    msdyn_isminor?: string;
    msdyn_isminorwithparentalconsent?: string;
    jobtitle?: string;
    lastusedincampaign?: string;
    lastonholdtime?: string;
    adx_identity_lastsuccessfullogin?: string;
    leadsourcecode?: string;
    adx_identity_locallogindisabled?: string;
    adx_identity_lockoutenabled?: string;
    adx_identity_lockoutenddate?: string;
    adx_identity_logonenabled?: string;
    managername?: string;
    managerphone?: string;
    familystatuscode?: string;
    marketingonly?: string;
    merged?: string;
    middlename?: string;
    adx_identity_mobilephoneconfirmed?: string;
    adx_modifiedbyipaddress?: string;
    adx_modifiedbyusername?: string;
    adx_identity_newpassword?: string;
    nickname?: string;
    numberofchildren?: string;
    msdyn_orgchangestatus?: string;
    ta_note?: string;

    onholdtime?: string;
    adx_organizationname?: string;

    pager?: string;
    participatesinworkflow?: string;
    adx_identity_passwordhash?: string;
    ta_patientorders?: string;
    ta_patientorders_date?: string;
    ta_patientorders_state?: string;
    paymenttermscode?: string;
    ta_drspecialty?: string;
    ta_dr_specialty?: string;
    msdyn_portaltermsagreementdate?: string;
    preferredappointmentdaycode?: string;

    preferredappointmenttimecode?: string;

    processid?: string;
    adx_profilealert?: string;
    adx_profilealertdate?: string;
    adx_profilealertinstructions?: string;
    adx_profileisanonymous?: string;
    adx_profilelastactivity?: string;
    adx_profilemodifiedon?: string;
    ta_ptan?: string;
    adx_publicprofilecopy?: string;
    ta_qbocustomerid?: string;
    ta_readytodelete?: string;
    customertypecode?: string;
    accountrolecode?: string;
    salutation?: string;

    adx_identity_securitystamp?: string;
    donotsendmm?: string;
    shippingmethodcode?: string;
    spousesname?: string;
    statuscode?: string;
    statecode?: string;
    suffix?: string;
    teamsfollowed?: string;
    telephone3?: string;
    territorycode?: string;
    timespentbymeonemailandmeetings?: string;
    adx_timezone?: string;
    timezoneruleversionnumber?: string;
    adx_identity_twofactorenabled?: string;
    adx_identity_username?: string;
    utcconversiontimezonecode?: string;
    versionnumber?: string;
    websiteurl?: string;
    yomifirstname?: string;
    yomifullname?: string;
    yomilastname?: string;
    yomimiddlename?: string;
    createdbyexternalparty?: string;
    transactioncurrencyid?: string;
    ta_dobid?: string;
    slainvokedid?: string;
    msa_managingpartnerid?: string;
    modifiedbyexternalparty?: string;
    originatingleadid?: string;
    owningbusinessunit?: string;
    preferredequipmentid?: string;
    adx_preferredlanguageid?: string;
    preferredserviceid?: string;
    defaultpricelevelid?: string;

    msdyn_segmentid?: string;
    slaid?: string;
    preferredsystemuserid: { azureactivedirectoryobjectid?: string };
    masterid: {
        birthdate?: string;
        firstname?: string;
        lastname?: string;
    };
    parent_contactid: {
        birthdate?: string;
        firstname?: string;
        lastname?: string;
    };
};

export type Provider = Patient;

export type CreatePatient = Partial<Omit<Patient, 'id'>>;
export type UpdatePatient = Partial<Omit<Patient, 'id'>>;
